# output_types.py
OUTPUT_TYPE_MAP = {
    "Ejecutable (.exe)": "exe",
    "Ejecutable Linux/Mac (sin extensión)": "bin",
    "Biblioteca dinámica Windows (.dll)": "dll",
    "Biblioteca dinámica Linux (.so)": "so",
    "Biblioteca dinámica Mac (.dylib)": "dylib",
    "Biblioteca estática Unix (.a)": "a",
    "Biblioteca estática Windows (.lib)": "lib",
    "Objeto compilado (.o/.obj)": "obj",
    "Módulo Python (.pyd/.so)": "pyd",
    "Rueda Python (.whl)": "whl",
    "Paquete Python (sdist .tar.gz)": "sdist",
    "Egg Python (.egg)": "egg",
    "Archivo Java Class (.class)": "class",
    "Archivo Java Archive (.jar)": "jar",
    "Android Archive (.aar)": "aar",
    "Android Package (.apk)": "apk",
    "iOS App (.ipa)": "ipa",
    "Paquete .NET (.dll/.exe o .nupkg)": "dotnet",
    "NuGet package (.nupkg)": "nupkg",
    "Archivo JAR ejecutable (.jar) con manifest": "jar-exec",
    "WAR Java Web Archive (.war)": "war",
    "EAR Java Enterprise Archive (.ear)": "ear",
    "Paquete Debian (.deb)": "deb",
    "Paquete RPM (.rpm)": "rpm",
    "Instalador Windows (.msi)": "msi",
    "PKG macOS (.pkg)": "pkg",
    "AppImage Linux (.AppImage)": "appimage",
    "Snap package (.snap)": "snap",
    "WebAssembly (.wasm)": "wasm",
    "Bundle macOS Framework (.framework)": "framework",
    "Plugin/Module Node (.tgz/.zip)": "nodepkg",
    "Binary Node (pkg) (.exe/.bin)": "nodebin",
    "Go binary": "go-bin",
    "Rust binary": "rust-bin",
    "Cargo release binary": "cargo-release",
    "Static site (dist folder)": "static-dist"
}
